version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '3000:${PORT}'
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    volumes:
      - ./:/app
    command: npm run start:dev
    depends_on: 
      - postgres

  postgres:
    image: 'postgres'
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./postgres-backups:/app/postgres-backups
